apiVersion: apps/v1
kind: Deployment
metadata:
  name: formula1
  labels:
    app: formula1-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: formula1-app
  template:
    metadata:
      labels:
        app: formula1-app
    spec:
      containers:
        - name: formula1
          image: damiov/formula1
---
apiVersion: v1
# Indicates this as a service
kind: Service
metadata:
  # Service name
  name: formula1
  namespace: default
spec:
  type: NodePort
  selector:
    # Selector for Pods
    app: formula1-app
  ports:
    # Port Map
    - port: 8501
      targetPort: 8501
      nodePort: 30080
