kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: formula1-compound-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30070
      - containerPort: 30020
        hostPort: 30010
      - containerPort: 30030
        hostPort: 30020
  - role: worker
  - role: worker
  - role: worker
